### PR TITLE
Merge in fixes made while preparing randoop testcase

### PR DESCRIPTION
**Pull request by tim-mccarthy**
- Switch to a newer branch of do-like-javac
- clean_project removes the dljc-out directory.
- Update/fix issues in corpus.json
- Add fetch.py script that fetches both corpus and dependencies.
- fetch_corpus no longer fails if corpus directory absent

### CODE REVIEW

**Comment by martinschaef** [comment]
@tim-mccarthy you have to assign this to someone ... my guess would be that @hsanchez should review it since he'll also merge this branch back to master.

**Comment by hsanchez** [comment]
@martinschaef I will review this today.

**Comment by hsanchez** [comment]
@tim-mccarthy can you pull the latest changes from master into this branch? Thanks

FYI, @martinschaef

**Comment by hsanchez** [comment]
@tim-mccarthy can you also run './fetch_dependencies.sh' after pulling from master?

**Comment by tim-mccarthy** [comment]
@hsanchez I merged master. fetch_dependencies.sh works fine on my machine.

**Comment by hsanchez** [comment]
@tim-mccarthy, I ran the latest ./fetch_dependencies.sh and. Its execution ends with a BUILD FAILED. One of the environment variables (:compileJava) is also marked as FAILED. 

Do you have an idea why this build is failing? 

[10-24-2016-logs.txt](https://github.com/aas-integration/integration-test2/files/549017/10-24-2016-logs.txt)

**Comment by tim-mccarthy** [comment]
@hsanchez The only thing that immediately pops out to me is that you're apparently running as a user named <usr-local-clone>, and that seems to me to be pretty likely to break not-so-carefully written shell scripts.

**Comment by hsanchez** [comment]
@tim-mccarthy, I curated the logs. I removed any user-specific paths (e.g., hsanchez/dev/) and replaced it with <user-local-clone>. I also replaced my actual username with <username>

**Comment by tim-mccarthy** [comment]
@hsanchez For me, that last phase looks like

[checker-working.txt](https://github.com/aas-integration/integration-test2/files/549163/checker-working.txt)

I have no idea what's going on in your case, it just seems to abruptly fail.

**Comment by hsanchez** [comment]
@tim-mccarthy I just tried the same thing but using Pascali. The build was a success. I have no idea what is going on my machine. Something in my environment is not right :-(. 

```
This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
:compileJava
:processResources UP-TO-DATE
:classes
:jar
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL
```

**Comment by wmdietl** [comment]
@hsanchez @CharlesZ-Chen Huascar, what is strange about your log `10-24-2016-logs.txt` is that you're building the jdk.jar, which the updated fetch script doesn't.

I looked through `https://github.com/pascaliUWat/ontology/blob/master/pascali-setup.sh` and don't see a reason why that would be happening.

It is also strange that your log contains

```
BUILD SUCCESSFUL
Total time: 7 seconds
Buildfile: /Users/<user-local-clone>/tools/checker-framework/build.xml
```

`pascali-setup.sh` contains `ant -f $JSR308/checker-framework/checker/build.xml jar` so the `checker-framework/build.xml` file should never be executed.

I can't think of a reason why this would happen on a clean check-out.
Is this Mac specific? Or does it work on a different Mac?

**Comment by tim-mccarthy** [comment]
@wmdietl @hsanchez I'm running on a Mac and it builds fine for me.

**Comment by hsanchez** [comment]
@martinschaef can you try this PR on your machine? 

FYI, @tim-mccarthy, @CharlesZ-Chen, @wmdietl

**Comment by hsanchez** [comment]
@tim-mccarthy, @wmdietl, @CharlesZ-Chen, @martinschaef 

I think I found the problem. The problem was an old version of do-like-javac that was in my PATH variable. I removed it and now the `fetch_dependencies.sh` finishes without errors. 

Also, the output entry `Buildfile: /Users/<user-local-clone>/tools/checker-framework/build.xml` that @wmdietl referenced in a previous comment is no longer there.

**Comment by tim-mccarthy** [comment]
The only thing that immediately pops out to me is that you're apparently
running as a user named <usr-local-clone>, and that seems to me to be
pretty likely to break not-so-carefully written shell scripts.

**Pull request merged**
