### PR TITLE
update dependecies building for checker-framework-inference and ontology type system

### PR DESCRIPTION
**Pull request by CharlesZ-Chen**

### CODE REVIEW

**Comment by wmdietl** [comment]
Please also remove the `TRAVIS_REPO_SLUG` lines on lines 3/4.
Otherwise these changes and the new script in `ontology/pascali-setup.sh` look good to me.
Thanks!

**Comment by CharlesZ-Chen** [comment]
Already remove it.

**Comment by martinschaef** [comment]
Let me loop in @hsanchez and @langkymus since they are working on the simprog branch. Will this change also work with the current version of the simprog branch? If so, please merge this and pull the changes into simprog.

**Comment by hsanchez** [comment]
@CharlesZ-Chen 

The ./fetch_dependencies script ends with a git error:

```
...
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

Do note there is nothing to commit on my end. I checked this new checked out branch was in sync with with master branch. (via pull command)...but there was nothing new to update. So the problem may be on your end. Having written that,  could you please update your PR branch and make sure it is in sync with the master branch? I think this will fix the above error. 

FYI @wmdietl, @martinschaef, @langkymus

**Comment by CharlesZ-Chen** [comment]
Hi Huascar, I've checked my branch with `aas-integration/integration-test2` master branch, and it still sync with the master branch. I've also tested the `fetch_dependencies` script of my branch on my machine, and it works fine.

Is the merge conflict error happens during executing the `fetch_dependencies` script? If yes, which step (during fetching which repo) has the conflict? Thanks!

**Comment by hsanchez** [comment]
@CharlesZ-Chen 

Here is some additional info from the logs pointing a CONFLICT warning:

```
remote: Total 402 (delta 265), reused 265 (delta 265), pack-reused 137
Receiving objects: 100% (402/402), 74.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (277/277), completed with 65 local objects.
From https://github.com/pascaliUWat/checker-framework-inference
 + 3c35748...a365484 master     -> origin/master  (forced update)
 * [new branch]      opprop-4demo-poly -> origin/opprop-4demo-poly
 * [new branch]      pascaliUWat-bk -> origin/pascaliUWat-bk
 * [new branch]      pascaliUWat-mergeOpprop -> origin/pascaliUWat-mergeOpprop
Auto-merging src/checkers/inference/VariableAnnotator.java
CONFLICT (content): Merge conflict in src/checkers/inference/VariableAnnotator.java
Removing src/checkers/inference/ConstraintManager.java
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by CharlesZ-Chen** [comment]
@hsanchez Did you already have a legacy copy of `checker-framework-inference` before running the `fetch_dependencies` script? We recently has force-updated the `checker-framework-inference` in pascaliUWat, the conflict might occur if you have a legacy copy. If that is the case, could you try to remove all checker-framework stuffs (checker-framework, checker-framework-inference, generic-type-inference-slover, ontology) in your machine and then running the `fetch_dependencies` script again? I think the updated `fetch_dependencies` script should work if you run it under a fresh directory (empty, new, noting legacy).

**Comment by martinschaef** [comment]
@CharlesZ-Chen @hsanchez @wmdietl where are we with this? It's still open. Can I be of any help?

**Comment by hsanchez** [comment]
@CharlesZ-Chen 

Sorry the delayed response. 

I don't have a legacy copy of checker-framework-inference 

"If that is the case, could you try to remove all checker-framework stuffs (checker-framework, checker-framework-inference, generic-type-inference-slover, ontology) in your machine and then running the fetch_dependencies script again?" >>> I did and still got the same conflict error. 

@tim-mccarthy, Tim... may this be related to dljc?

**Comment by CharlesZ-Chen** [comment]
@hsanchez Here are my steps of testing  the `fetch-dependencies` script on the branch (`build-CFI-ontology`) that I made this PR from:
1. `mkdir sandbox`
2. `cd sandbox && git clone https://github.com/CharlesZ-Chen/integration-test2.git --branch build-CFI-ontology`
3. `./fetch_dependencies.sh`

The result is successful after running around 5mins.

In your provided infos, it seems this merge conflict is in Checker-framework-inference:

> Auto-merging src/checkers/inference/VariableAnnotator.java
> CONFLICT (content): Merge conflict in src/checkers/inference/VariableAnnotator.java

I still cannot see the reason as the script of building CFI (`pascali-setup.sh`) actually doing this:

``` bash
#...
CUR_DIR=$(pwd)
export JSR308=$(cd ../ && pwd)
#...
##### build checker-framework-inference
if [ -d $JSR308/checker-framework-inference ] ; then
    (cd $JSR308/checker-framework-inference && git pull)
else
    (cd $JSR308 && git clone --depth 1 https://github.com/"$REPO_SITE"/checker-framework-inference.git)
fi
#...
```

Thus if you don't have any previous copy of CFI, it should directly clone a new one from pascaliUWat repo and cannot have any merge conflict as there should be just a simple cloning step...

Could you provide a re-produce steps for me to see why there is a merge conflict?

Thanks!

**Comment by hsanchez** [comment]
@martinschaef

I am doing the same thing you are doing. 

@martinschaef, @CharlesZ-Chen 

Let me do a cleanup and will let you know If I am still getting that error.  Otherwise, I will merge this PR into master.

**Comment by hsanchez** [comment]
@CharlesZ-Chen, @martinschaef 

I am not getting the error. 

This is what I did. 

(1) I removed all previous clones of integration-test2 from my machine. Then, (2) I cloned the integration-test2 repo, (3) checked out Charles's PR, and (4) ran the './fetch_dependencies.sh'

I will merge it now.

**Pull request merged**
