### PR TITLE
refactor map2annotation script

### PR DESCRIPTION
**Pull request by CharlesZ-Chen**
- make `map2annotation` a python module

- provides command line interface for individually running Ontology System by giving mappings to this script

- provides json file examples

### CODE REVIEW

**Comment by martinschaef** [comment]
@CharlesZ-Chen thanks for the PR. Your script is currently called from backend.py. Could you update that and make sure that ./run_mini.sh still works?

**Comment by CharlesZ-Chen** [comment]
@martinschaef Just a quick question:

What would be a good sign of `./run_mini.sh` works?

I tried to directly run `run_mini.sh` in `master` branch as a test, and it would throw some exception from daikon in my machine:

```
Daikon version 5.4.1, released October 4, 2016; http://plse.cs.washington.edu/daikon.
Reading declaration files Processing trace data; reading 1 dtrace file:
Exception in thread "main" java.lang.Error: java.io.EOFException: Unexpected end of ZLIB input stream
	at daikon.FileIO.read_data_trace_files(FileIO.java:923)
	at daikon.FileIO.read_data_trace_files(FileIO.java:889)
	at daikon.Daikon.process_data(Daikon.java:2014)
	at daikon.Daikon.mainHelper(Daikon.java:563)
	at daikon.Daikon.main(Daikon.java:457)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.LineNumberReader.readLine(LineNumberReader.java:201)
	at daikon.FileIO.read_data_trace_record(FileIO.java:1437)
	at daikon.FileIO.read_data_trace_file(FileIO.java:1363)
	at daikon.FileIO.read_data_trace_files(FileIO.java:907)
	... 4 more
```
Is this normal or I missing some pre-steps for running  `run_mini.sh`? 

Thanks,

**Comment by martinschaef** [comment]
can you delete the `tool` folder and re-run ./fetch-dependencies.sh? This should fix the problem

**Comment by CharlesZ-Chen** [comment]
Will try it.

**Comment by markro49** [comment]
definitely not normal.  most likely there was a problem with the prior chicory run.

**Comment by CharlesZ-Chen** [comment]
@martinschaef Already updated backend.py. Tested `run_mini.sh` in my local machine and it seems works fine:

```
===========================================================================
Sort07:::OBJECT
this has only one value
===========================================================================
Sort07.Sort07():::EXIT
===========================================================================
Sort07.sort(int[]):::ENTER
array != null
array[] elements >= -1
===========================================================================
Sort07.sort(int[]):::EXIT
array[] <= orig(array[]) (lexically)
array[] elements >= -1
array[] sorted by <=
===========================================================================
org.junit.Assert.assertNotNull(java.lang.Object):::ENTER
object.getClass().getName() == int[].class
===========================================================================
org.junit.Assert.assertNotNull(java.lang.Object):::EXIT
===========================================================================
org.junit.Assert.assertNotNull(java.lang.String, java.lang.Object):::ENTER
message == null
object.getClass().getName() == int[].class
===========================================================================
org.junit.Assert.assertNotNull(java.lang.String, java.lang.Object):::EXIT
===========================================================================
org.junit.Assert.assertTrue(java.lang.String, boolean):::ENTER
message == null
condition == true
===========================================================================
org.junit.Assert.assertTrue(java.lang.String, boolean):::EXIT
Exiting Daikon.

********* END OF BACKEND **********
```

**Comment by martinschaef** [comment]
Yes, that looks good. Thx!

**Pull request merged**
