### PR TITLE
add annotation map script

### PR DESCRIPTION
**Pull request by CharlesZ-Chen**
This PR is not ready to be merged as I still need to clarify some protocols:
@martinschaef 

- JSON file location and format: where should I expect to find JSON file(s)? I currently come up with these two options but I'm not sure which one is more proper for our project:

1) under each project dir, we have a JSON file named `project_name.json`, with the format like:

```json
{
    "mappings": 
        [{"fields": xxx, "label": xxx},
         {"fields": xxx, "label": xxx},
        ]
}
```

2) there is only one single JSON file that contains all projects informations:

```json
{
    "projectA_name": 
        [{"fields": xxx, "label": xxx},
         {"fields": xxx, "label": xxx},
        ],
    "projectB_name": 
        [{"fields": xxx, "label": xxx},
         {"fields": xxx, "label": xxx},
        ]
}
```
Note: in option `2` it would be better if the JSON file could group mappings by project as it makes me a lot easier to do tasks on project base.

- the proper location of this script itself: where is the proper location of this script?
---

note of changes of this PR:

add a script that doing below tasks:

- takes a JSON file contains `fields` and `label` info
- each `label` becomes a new @Ontology constant
- convert the `fields` info into an AFU file to annotate the fields with their corresponding new Ontology
- insert the AFU file into the project sources
- run type inference to propagate the annotations from the fields

---

In addition, due to an [issue](https://github.com/typetools/annotation-tools/issues/36) in `annotation-file-utilities`, currently we need to refactor projects' source code to eliminate simultaneous declarations like below to make `insert-annotations-to-source` works correctly:

```java
//simultaneous declarations
Object a, b, c;

//refactor to
Object a;
Object b;
Object c;
```
 
As a workaround we could manually or using some reformatting tools to eliminate imultaneous declarations in the source code before passing it to insert annotations.

### CODE REVIEW

**Comment by martinschaef** [comment]
@CharlesZ-Chen, Thanks for the quick work 👍 - let me loop in @hsanchez  as well since he wrote most of this code. 

---
## File format
Currently, we just collect all fields in all classes of all project and produce this one giant blob that we gave you. However, it shouldn't be too hard to add a bit more structure. 
One problem, however, is that we build this json file from soot by iterating over a list of classpath entries, so we don't know exactly what a 'project' is. @hsanchez what's your take on this?

@CharlesZ-Chen another issue that might occur is that we give you a class or field for which you cannot find source code (since we look at bytecode only). In this case, just ignore the class.

---
## Code style
Regarding the refactoring for your [issue](https://github.com/typetools/annotation-tools/issues/36), there is little I can, because the code comes from the corpus. But feel free to run something like [indent](https://www.gnu.org/software/indent/) on the code during pre-processing.

**Comment by hsanchez** [comment]
@CharlesZ-Chen 

As @martinschaef pointed out, it is difficult to determine the source (or project) of these fields because of soot. It would be hard for us to collect that type of information. I would assume that it would be easier for your tool to collect that type of information (by keeping an index) since it was not constrained by soot. 

Here is a snippet of the JSON file we produce....
```
		{
		 "fields":[
			"com.vesperin.pack.parser.visitors.ImportReferencesVisitor.selection"
                        "com.vesperin.pack.utils.SourceRange.selection"
		 ],
		 "label":[
			"selection"
		 ]
                }
```

**Comment by CharlesZ-Chen** [comment]
@hsanchez Ok... Now I changed my script to also generate a single jaif file for the whole corpus as it actually very hard to mapping the `fields` back to the project that them belongs to...

At the moment, the protocol of this script to be used as a module would be:

```python
import map2annoAndAfu

json_file = "the absolute path of your json file contains the mapping info"
map2annoAndAfu.main(json_file)
```

@martinschaef @hsanchez  Please let me know whether this protocol is fine to us or I needs some changes on that.

---
@martinschaef  For the formatting issue, I've tried several java formatters, include `google-java-format`, `jIndent`, and some online java formatters. None of them could process the simultaneous declarations at the moment.

I've filed an issue on `google-java-format`:

https://github.com/google/google-java-format/issues/104

But I'm not sure when and will they provide some feedbacks to me...

@martinschaef  If I couldn't find a works formatter in a short period, is the "manually sanitized" workaround works for us?

Thanks,

Charles

**Comment by martinschaef** [comment]
@CharlesZ-Chen yes, theoretically we can sanitize things manually. However, the problem is that we pull these projects from github in the fetch-corpus script. The easiest thing is probably to add diff files and patch things locally at the end of fetch-dependencies. Otherwise we would have to fork all these corpus projects.

**Comment by hsanchez** [comment]
@CharlesZ-Chen 

With respect to the formatting thing, what you are describing is not formatting. It is refactoring. If you need a basic formatter, then try checkstyle (https://github.com/checkstyle/checkstyle). 

Otherwise, if you want a tool that supports basic refactorings (and code formatting), then probably my library https://github.com/vesperin/vesper could help you. Unfortunately, the refactoring you are describing is not supported. Therefore, you will need to implement it.  Check the main class `Vesper` for specific details of how to use it.

**Comment by hsanchez** [comment]
The PR looks good. Unless @martinschaef has an issue, then I think this PR can be merged into master. I will go ahead and merge it in a few minutes, so I can give @martinschaef a chance to reject this decision.

**Comment by CharlesZ-Chen** [comment]
>With respect to the formatting thing, what you are describing is not formatting. It is refactoring. If you need a basic formatter, then try checkstyle (https://github.com/checkstyle/checkstyle).
 Otherwise, if you want a tool that supports basic refactorings (and code formatting), then probably my library https://github.com/vesperin/vesper could help you.

@hsanchez Thanks for the information. I'm still looking around to find a way of doing that. I'll make another PR once I've solved the "simultaneous declarations" issue.

@martinschaef @hsanchez Besides the "simultaneous declarations" issue, this PR also depends on a fix in `annotation-files-utils` here:

https://github.com/opprop/annotation-tools/pull/2

Once this fix has been merged and propagated to our `pascaliUWat` and the "simultaneous declarations" issue has been solved, the script in this PR should works fine.

**Comment by hsanchez** [comment]
Thanks @CharlesZ-Chen for the info. 

Let's wait for the 'annotation-files-utils' to be fixed before we merge this PR. @CharlesZ-Chen, when do you think the fix you mentioned will go in?

FYI, @martinschaef

**Comment by martinschaef** [comment]
Thx. @CharlesZ-Chen @hsanchez are you guys around for a sync call? I need to get an idea which part of this presentable next Monday. My skype ID is 'schaef'

**Comment by CharlesZ-Chen** [comment]
@hsanchez I think I can do a fast propagation today of this fix to `pascaliUWat` ahead of merging into upstream if we need this urgently.

@martinschaef I'm available anytime for a sync call. My skype ID is 'charleszhuochen@outlook.com'

**Pull request merged**
