### PR TITLE
Simprog test

### PR DESCRIPTION
**Pull request by hsanchez**
created PR for code reviewing purposes

### CODE REVIEW

**Comment by martinschaef** [comment]
Thx, will look into it later today. Please always assign people if u want stuff to be reviewed since some folks have the basic notifications disabled.

**Comment by martinschaef** [comment]
Btw., did u check with @langkymus if he pushed his latest changes? If not, please do so so that we can delete the branch.

**Comment by hsanchez** [comment]
@martinschaef, I emailed @langkymus asking if the `simprog test` branch contains all his latest changes and if it does not to go ahead and push them to it.

**Comment by hsanchez** [comment]
@langkymus can you push your latest changes to this branch? Thanks.

**Comment by langkymus** [comment]
Yes, I did to simprog.

**Comment by hsanchez** [comment]
@langkymus 

I am getting a bunch of related errorr after running `python backend.py -c clusters.json -d ouput -g`. They are related to the prog2dfg.jar file. Can you try to push a new prog2dfg.jar file?  Here is a snapshot of what I got:

```
...
Error: Invalid or corrupt jarfile /Users/hsanchez/dev/it2/libs/prog2dfg.jar
Running java -jar /Users/hsanchez/dev/it2/libs/prog2dfg.jar -o /Users/hsanchez/dev/it2/corpus/jmonkeyengine/dljc-out/_jme3-lwjgl_build_classes_main -j /Users/hsanchez/dev/it2/corpus/jmonkeyengine/jme3-lwjgl/build/classes/main -all -source /Users/hsanchez/dev/it2/corpus/jmonkeyengine/__java_file_names.txt
...
Error: Invalid or corrupt jarfile /Users/hsanchez/dev/it2/libs/prog2dfg.jar
Running java -jar /Users/hsanchez/dev/it2/libs/prog2dfg.jar -o /Users/hsanchez/dev/it2/corpus/jmonkeyengine/dljc-out/_jme3-lwjgl_build_classes_main -j /Users/hsanchez/dev/it2/corpus/jmonkeyengine/jme3-lwjgl/build/classes/main -all -source /Users/hsanchez/dev/it2/corpus/jmonkeyengine/__java_file_names.txt
...
Error: Invalid or corrupt jarfile /Users/hsanchez/dev/it2/libs/prog2dfg.jar
Running java -jar /Users/hsanchez/dev/it2/libs/prog2dfg.jar -o /Users/hsanchez/dev/it2/corpus/jmonkeyengine/dljc-out/_jme3-lwjgl_build_classes_main -j /Users/hsanchez/dev/it2/corpus/jmonkeyengine/jme3-lwjgl/build/classes/main -all -source /Users/hsanchez/dev/it2/corpus/jmonkeyengine/__java_file_names.txt
....
Gathering kernels from projects jreactphysics3d and jbox2d and react and jmonkeyengine
Traceback (most recent call last):
  File "backend.py", line 80, in <module>
    main()
  File "backend.py", line 77, in main
    gather_kernels(pl, os.path.join(common.WORKING_DIR, args.dir, project+"_kernel.txt"))
  File "backend.py", line 27, in gather_kernels
    with open(project_kernel_file_path, "r") as fi: corpus_kernel_file_handle.write(fi.read())
IOError: [Errno 2] No such file or directory: u'/Users/hsanchez/dev/it2/corpus/jreactphysics3d/dljc-out/_target_classes/kernel.txt'
```

FYI, @martinschaef

**Comment by langkymus** [comment]
Hmmm, I am pretty sure I didn't touch prog2dfg.jar. @martinschaef, any idea?

**Comment by martinschaef** [comment]
That error happens if you build that jar using the wrong command ... since fetch_dependency.sh still fetches that file from dropbox, I'd assume that has never been updated. Just take the latest version of the jar (either what was used for the experiments or build it from head) and put it somewhere more predictable than dropbox

**Comment by langkymus** [comment]
@hsanchez @martinschaef  I have put the version of prog2dfg.jar that I used in the FASE experiments in /tmp on pascali for now.

**Comment by martinschaef** [comment]
Excellent ... Huascar, can you update that? I'll also move prog2dfg to a public git later, then we can simply use github releases.
I went through the paper again, and I'm still not really happy with the evaluation. Mostly due to time and space constraints. Let's think about how we would run an evaluation if there was no page limit it we had an arbitrary amount of time. How would you evaluate the approach? What would the research questions be?
Let's free up some time after the Tue phone call to discuss this ...

**Comment by hsanchez** [comment]
@martinschaef and @langkymus 

Ok. I am using now the prog2dfg.jar found at the mentioned tmp folder. Now, I am getting a different set of errors:

```
...
Thread hack failed
Thread hack failed
Thread hack failed
Exception in thread "main" java.lang.RuntimeException: Failed to apply jb to <jme3test.model.anim.TestSpatialAnim: void simpleInitApp()>
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1804)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at com.sri.prog2dfg.SootToGraph.processSootMethod(SootToGraph.java:180)
    at com.sri.prog2dfg.SootToGraph.processSootClass(SootToGraph.java:97)
    at com.sri.prog2dfg.SootToGraph.run(SootToGraph.java:52)
    at com.sri.prog2dfg.Main.main(Main.java:40)
Caused by: java.lang.RuntimeException: This operation requires resolving level HIERARCHY but com.jme3.animation.Track is at resolving level DANGLING
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(com.jme3.animation.Track,HIERARCHY);
Otherwise, try whole-program mode (-w).
    at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:152)
    at soot.SootClass.checkLevel(SootClass.java:138)
    at soot.FastHierarchy.canStoreClass(FastHierarchy.java:277)
    at soot.FastHierarchy.canStoreType(FastHierarchy.java:209)
    at soot.FastHierarchy.canStoreType(FastHierarchy.java:257)
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.ancestor_(BytecodeHierarchy.java:253)
    at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.ancestor(BytecodeHierarchy.java:233)
    at soot.jimple.toolkits.typing.fast.TypeResolver$CastInsertionUseVisitor.visit(TypeResolver.java:212)
    at soot.jimple.toolkits.typing.fast.UseChecker.handleInvokeExpr(UseChecker.java:138)
    at soot.jimple.toolkits.typing.fast.UseChecker.caseInvokeStmt(UseChecker.java:210)
    at soot.jimple.internal.JInvokeStmt.apply(JInvokeStmt.java:100)
    at soot.jimple.toolkits.typing.fast.UseChecker.check(UseChecker.java:122)
    at soot.jimple.toolkits.typing.fast.TypeResolver.insertCasts(TypeResolver.java:411)
    at soot.jimple.toolkits.typing.fast.TypeResolver.minCasts(TypeResolver.java:422)
    at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:158)
    at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:131)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:66)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:89)
    at soot.Pack.apply(Pack.java:132)
    at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1802)
    ... 6 more
Running java -jar /Users/hsanchez/dev/it2/libs/prog2dfg.jar -o /Users/hsanchez/dev/it2/corpus/jmonkeyengine/dljc-out/_jme3-ios_build_classes_main -j /Users/hsanchez/dev/it2/corpus/jmonkeyengine/jme3-ios/build/classes/main -all -source /Users/hsanchez/dev/it2/corpus/jmonkeyengine/__java_file_names.txt
Cannot inline <com.jme3.system.ios.JmeIosSystem: void showDialog(java.lang.String)>
Number of graphs generated: 158
...
Gathering kernels from projects jreactphysics3d and jbox2d and react and jmonkeyengine
Traceback (most recent call last):
  File "backend.py", line 80, in <module>
    main()
  File "backend.py", line 77, in main
    gather_kernels(pl, os.path.join(common.WORKING_DIR, args.dir, project+"_kernel.txt"))
  File "backend.py", line 27, in gather_kernels
    with open(project_kernel_file_path, "r") as fi: corpus_kernel_file_handle.write(fi.read())
IOError: [Errno 2] No such file or directory: u'/Users/hsanchez/dev/it2/corpus/jbox2d/dljc-out/_jbox2d-testbed_target_classes/kernel.txt'
```

@langkymus or @martinschaef .. can you try to review this PR from your mac (not from Pascali) using a fresh clone of the integration-tests2 repo? 

These are the steps I followed

```
1.  git clone https://github.com/aas-integration/integration-test2.git
2. cd integration-test2
3. git fetch origin
4. git fetch origin pull/4/head:simprogPR (
5. git checkout simprogPR
6. python fetch.py
7.  (assuming we have an output dir and a file clusters.json), python backend.py -c clusters.json -d output -g
```

**Comment by martinschaef** [comment]
I guess we have to harden a bit. I'll add some exception handling to proc2dfg once I get home.
@langkymus can you also make sure that a missing kernel file does not crash the script but only skips this project?

**Comment by martinschaef** [comment]
@hsanchez just uploaded this version https://github.com/aas-integration/prog2dfg/releases/tag/v0.1

**Comment by martinschaef** [comment]
I accidentally merged it while updating the dependency ... @hsanchez @tim-mccarthy @langkymus  let's test master again to make sure everything works. Then we start adding the image processing stuff.
I'll also add a dependency for my jar that computes the clusters.

**Pull request merged**
